"""add password reset tokens table

Revision ID: 135b719f5dfb
Revises: 862636b214f8
Create Date: 2025-06-29 20:28:08.886868

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "135b719f5dfb"
down_revision: Union[str, Sequence[str], None] = "862636b214f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("clickevent")
    op.create_index(
        op.f("ix_passwordresettoken_token"),
        "passwordresettoken",
        ["token"],
        unique=False,
    )
    op.create_foreign_key(None, "passwordresettoken", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "passwordresettoken", type_="foreignkey")
    op.drop_index(op.f("ix_passwordresettoken_token"), table_name="passwordresettoken")
    op.create_table(
        "clickevent",
        sa.Column(
            "ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column(
            "user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "referer", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("country", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column(
            "device_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("browser", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("link_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "clicked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["link_id"], ["link.id"], name=op.f("clickevent_link_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("clickevent_pkey")),
    )
    # ### end Alembic commands ###
