"""add email logging table

Revision ID: a6fe5550f629
Revises: c11a601cb64b
Create Date: 2025-06-30 00:33:43.255506

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "a6fe5550f629"
down_revision: Union[str, Sequence[str], None] = "c11a601cb64b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_emaillog_recipient_email"), table_name="emaillog")
    op.drop_table("emaillog")
    op.drop_table("clickevent")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clickevent",
        sa.Column(
            "ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column(
            "user_agent", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "referer", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column("country", sa.VARCHAR(length=2), autoincrement=False, nullable=True),
        sa.Column(
            "device_type", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("browser", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("link_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "clicked_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["link_id"], ["link.id"], name=op.f("clickevent_link_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("clickevent_pkey")),
    )
    op.create_table(
        "emaillog",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "email_type",
            postgresql.ENUM(
                "WELCOME", "PASSWORD_RESET", "ANALYTICS_SUMMARY", name="emailtype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("recipient_email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("success", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("error_message", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "analytics_period_start",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "analytics_period_end",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("emaillog_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("emaillog_pkey")),
    )
    op.create_index(
        op.f("ix_emaillog_recipient_email"),
        "emaillog",
        ["recipient_email"],
        unique=False,
    )
    # ### end Alembic commands ###
